# Generated by Django 3.1.4 on 2024-02-02 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20240202_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления 1 мин.'), django.core.validators.MaxValueValidator(1000, message='Максимальное время приготовления 1000 мин.')], verbose_name='Время приготовленияв минутах'),
        ),
    ]
