# Generated by Django 3.1.4 on 2024-02-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20240204_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
